student:
 #username: forezp
 age: 12


# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot
    password: love
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.56.128
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-idle: 500
      min-idle: 0



#mybatis的配置

mybatis:
  mapper-locations: classpath:mapper/*.xml

#pagehelper分页插件配置
pagehelper:
  helper-dialect:mysql


